import { Fault } from './faults';

export const mockTasks: Fault[] = [
  {
    id: 'p1',
    title: 'Sporto baro renovacija',
    description: 'Atnaujinti baro baldus ir apšvietimą.',
    clubId: 'OGM',
    clubName: 'SG Ogmios',
    status: 'Vykdoma',
    type: 'PROJEKTAS',
    entityType: 'project',
    phase: 'Planuojama',
    createdAt: Date.now() - 3600000 * 24 * 7,
    updatedAt: Date.now() - 3600000 * 2,
    assigneeId: 'ops_1',
    assigneeName: 'Operacijų vadovas',
    priority: 'high',
    slaHours: 0,
    assignedTo: 'Operacijų vadovas',
    comments: [],
    media: [],
    watchers: [],
    rejected: false,
    rejectReason: '',
    updatedBy: 'Operacijų vadovas',
    code: 'P-1',
    nextAction: {
      text: 'Pasirašyti sutartį su rangovais',
      dueDate: new Date(Date.now() + 86400000).toISOString()
    },
    history: []
  },
  {
    id: 't1',
    title: 'Sukurti SOP – Bėgimo takų tepimas',
    description: 'Sukurti SOP pagal pasikartojantį gedimą Akropolio klube.',
    clubId: 'OGM',
    clubName: 'SG Ogmios',
    status: 'Naujas',
    type: 'SOP',
    entityType: 'sop',
    createdAt: Date.now() - 3600000 * 5,
    updatedAt: Date.now() - 3600000 * 5,
    relatedFaultId: 'f3',
    assigneeId: 'ops_1',
    assigneeName: 'Operacijų vadovas',
    priority: 'medium',
    slaHours: 0,
    assignedTo: 'Operacijų vadovas',
    comments: [],
    media: [],
    watchers: [],
    rejected: false,
    rejectReason: '',
    updatedBy: 'Operacijų vadovas',
    code: 'T-1',
    history: []
  },
  {
    id: 't2',
    title: 'Rebrandingas - iškabos',
    description: 'Pakeisti iškabas visuose klubuose.',
    clubId: 'SG_VYT',
    clubName: 'SG Vytauto pr',
    status: 'Kada nors',
    type: 'REBRANDING',
    entityType: 'task',
    createdAt: Date.now() - 3600000 * 24 * 30,
    updatedAt: Date.now() - 3600000 * 24 * 30,
    assigneeId: 'ops_1',
    assigneeName: 'Operacijų vadovas',
    priority: 'low',
    slaHours: 0,
    assignedTo: 'Operacijų vadovas',
    comments: [],
    media: [],
    watchers: [],
    rejected: false,
    rejectReason: '',
    updatedBy: 'Operacijų vadovas',
    code: 'T-2',
    history: []
  }
];
