import type { AuthUser } from "./types";

// Mock credentials for local permissions testing only.
export const MOCK_PASSWORD = "Test123!";

export const mockUsers: AuthUser[] = [
  {
    id: "u1",
    name: "Miglė",
    email: "migle@fitsport.lt",
    role: "COORDINATOR",
    region: "Vilnius",
    regionAccess: ["Vilnius"],
    modulePermissions: ["darbai", "gedimai", "periodiniai", "analytics", "orders"],
    is_active: true,
  },
  {
    id: "u2",
    name: "Tomas",
    email: "tomas@fitsport.lt",
    role: "COORDINATOR",
    region: "Kaunas",
    regionAccess: ["Kaunas"],
    modulePermissions: ["darbai", "gedimai", "periodiniai", "analytics", "orders"],
    is_active: true,
  },
  {
    id: "u4",
    name: "Jonas",
    email: "jonas@fitsport.lt",
    role: "COORDINATOR",
    region: "Klaipėda",
    regionAccess: ["Klaipėda"],
    modulePermissions: ["darbai", "gedimai", "periodiniai", "analytics", "orders"],
    is_active: true,
  },
  {
    id: "u6",
    name: "Buhalterija",
    email: "accounting@fitsport.lt",
    role: "ACCOUNTING",
    region: "ALL",
    regionAccess: ["ALL"],
    modulePermissions: ["orders", "audit"],
    is_active: true,
  },
  {
    id: "u3",
    name: "Admin User",
    email: "admin@fitsport.lt",
    role: "OPS",
    region: "ALL",
    regionAccess: ["ALL"],
    modulePermissions: [
      "darbai",
      "gedimai",
      "periodiniai",
      "admin",
      "analytics",
      "audit",
      "orders",
      "zmones",
      "ceo",
    ],
    is_active: true,
  },
  {
    id: "u5",
    name: "Super Admin",
    email: "superadmin@fitsport.lt",
    role: "SUPER_ADMIN",
    region: "ALL",
    regionAccess: ["ALL"],
    modulePermissions: [
      "darbai",
      "gedimai",
      "periodiniai",
      "admin",
      "analytics",
      "audit",
      "orders",
      "zmones",
      "ceo",
    ],
    is_active: true,
  },
  {
    id: "auth-superadmin",
    name: "Super Admin",
    email: "superadmin@sportgates.lt",
    role: "SUPER_ADMIN",
    region: "ALL",
    regionAccess: ["ALL"],
    modulePermissions: [
      "darbai",
      "gedimai",
      "periodiniai",
      "admin",
      "analytics",
      "audit",
      "orders",
      "zmones",
      "ceo",
    ],
    is_active: true,
  },
  {
    id: "auth-ops",
    name: "OPS Komanda",
    email: "ops@sportgates.lt",
    role: "OPS",
    region: "ALL",
    regionAccess: ["ALL"],
    modulePermissions: [
      "darbai",
      "gedimai",
      "periodiniai",
      "admin",
      "analytics",
      "audit",
      "orders",
      "zmones",
      "ceo",
    ],
    is_active: true,
  },
  {
    id: "auth-marketing",
    name: "Marketingas",
    email: "marketing@sportgates.lt",
    role: "CS",
    region: "Vilnius",
    regionAccess: ["Vilnius"],
    modulePermissions: ["darbai", "gedimai", "analytics", "zmones"],
    is_active: true,
  },
];
